version: '3.4'

services: 
  pg: 
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
  app: 
    image: kilichips/kiliapi:v1
    ports: ["3000:3000"]
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
  
