version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis: 
    image: redis
    ports: 
      - "6379:6379"
  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/kilichips-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment: 
      REDIS_URL: redis://redis:6379
