version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_URL: postgres://admin:${{secrets.POSTGRES_PASSWORD}}@localhost:5432/test
      POSTGRES_DB: test
      POSTGRES_HOST: postgres
  redis: 
    image: redis
    ports: 
      - "6379:6379"
  rails:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/kilichips-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment: 
      REDIS_URL: redis://redis:6379
