name: CI
on: [push, pull_request]
jobs: 
  test: 
    runs-on: ubuntu-latest
    services: 
      postgres: 
        image: postgres
        env: 
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_URL: postgres://admin:${{secrets.POSTGRES_PASSWORD}}@localhost:5432/test
          POSTGRES_DB: test
          POSTGRES_HOST: postgres

        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis: 
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: 2.5.x
      - name: Build and run tests
        env: 
          POSTGRES_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: 
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install 
          bundle exec rails db:prepare
          bundle exec rspec
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop:'~>0.81.0' # https://docs.rubocop.org/en/stable/installation/
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.rubocop.yml
      - name: Rubocop Report
        run: rubocop --color
